{
    'name': 'Fluxdock Theme specific development',
    'description': 'Custom Theme for the fluxdock website.',
    'version': '11.0.1.0.0',
    'author': 'Camptocamp',
    'data': [
        'templates/assets.xml',
        'templates/layout/misc.xml',
        'templates/layout/header.xml',
        'templates/layout/footer.xml',
        'templates/layout/menu.xml',
        'templates/layout/listing.xml',
        'templates/layout/layout_2_cols.xml',
        'templates/editor/editor_options.xml',
        'templates/editor/snippets.xml',
        'templates/forms/search_form.xml',
        'templates/forms/widgets.xml',
        'templates/login.xml',
        'templates/mosaic.xml',
        'templates/status_msg.xml',
        'templates/email.xml',
        'templates/design_test/layout_2_cols_test.xml',
        'templates/design_test/gradients_test.xml',
        'pages/homepage.xml',
    ],
    'category': 'Theme/Creative',
    'depends': [
        'cms_status_message',
        'cms_delete_content',
        'cms_form',
        'cms_notification',
        'cms_toolbar',
        'http_routing',
        'mail_digest',
        'website',
        # need for personal menu content (see layout.xml)
        'website_partner',
    ],
    'post_load': 'patch_web_asset',
}
