{
    'name': 'Fluxdock Theme specific development',
    'description': 'Custom Theme for the fluxdock website.',
    'version': '1.0',
    'author': 'Pierre Sandrin',
    'data': [
        'views/layout.xml',
        'views/snippets.xml',
        'views/options.xml',
        'views/assets.xml',
        'views/status_message.xml',
        'views/listing.xml',
        'views/widgets.xml',
        'views/mosaic.xml',
        'pages/homepage.xml',
    ],
    'category': 'Theme/Creative',
    'depends': ['website',
                'website_blog',
                'website_portal',
                ],
}
