FROM camptocamp/odoo-project:9.0-1.3.0
MAINTAINER Camptocamp

COPY oerpscenario /opt/odoo/oerpscenario
COPY bin/oerpscenario /opt/odoo/bin/oerpscenario

ENV ADDONS_PATH=/opt/odoo/local-src,/opt/odoo/external-src/server-tools,/opt/odoo/src/addons,/opt/odoo/external-src/vertical-association
